spring:
  datasource:
    url: ${POSTGRESQL_URL}
    username: ${POSTGRESQL_USERNAME}
    password: ${POSTGRESQL_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  mvc:
    static-path-pattern: /static/**
  config:
    import: classpath:/properties/dev/initial_data.yml, optional:file:.env[.properties]

python:
  server:
    url: ${PYTHON_SERVER_URL}